### ISSUE TITLE
Layout on smaller iDevice needs scaling

### ISSUE THREAD

**Issue by AndyDentFree** [realm-demos/realm-loginkit#13]
Using it to test the server, tried on a iPhone SE simulator.

As you can see in the image below, there are some ugly overlaps. It gets worse if you press the _Register a New Account_ button.

![image](https://cloud.githubusercontent.com/assets/1586093/22379902/4dc4ae12-e4f6-11e6-862b-2b532afd59ed.png)

**Comment by TimOliver** [comment]
I noticed this as well, but you beat me to making an issue for it!

Fixed in #15. :)
