### ISSUE TITLE
RealmLoginKit crashes after fresh launch w/Save Credentials "off"

### ISSUE THREAD

**Issue by dhmspector** [realm-demos/realm-loginkit#14]
(copied from @austinzheng's initial report in the PermissionTester repo)

Upon restarting the app, I get a crash in one of the lines of code below.

```swift
private func loadLoginCredentials() {
    let userDefaults = UserDefaults.standard
    serverURL = userDefaults.object(forKey: LoginViewController.serverURLKey) as! String?
    email = userDefaults.object(forKey:  LoginViewController.emailKey) as! String?
    password = userDefaults.object(forKey: LoginViewController.passwordKey) as! String?
}
```

The error is: `Could not cast value of type '__NSCFData' (0x107d59680) to 'NSString' (0x105193c40).`.

Update:
I believe it happened after I logged in with the "save credentials" switch toggled off, and killed the app and relaunched it. It happened every time I relaunched the app in the iOS Simulator until I reset the simulator and reinstalled the app.

**Comment by TimOliver** [comment]
Fixed in #16! :)
