### ISSUE TITLE
App name is truncated if too long

### ISSUE THREAD

**Issue by dhmspector** [realm-demos/realm-loginkit#8]
As displayed on the login panel, the app name will be truncated if it is too long

![simulator screen shot jan 24 2017 8 33 19 am](https://cloud.githubusercontent.com/assets/21057/22256534/e8d3da20-e20f-11e6-9d82-94cef2a119c4.png)

**Comment by TimOliver** [comment]
I refactored the text label slightly in #15 to add some more padding on either side, and to dynamically shrink if the text is too long.
